# Generated by Django 3.2.2 on 2021-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0002_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone_no',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
    ]
