from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_index, name='index'),
    path('medicine/', views.MedicineListView.as_view(), name='medicine-list'),
    path('medicine/create', views.MedicineCreateView.as_view(), name='medicine-create'),
    path('medicine/delete/<int:pk>', views.MedicineDeleteView.as_view(), name='medicine-delete'),
    path('medicine/update/<int:pk>', views.MedicineUpdateView.as_view(), name='medicine-update'),
    path('medicine/detail/<int:pk>', views.MedicineDetailView.as_view(), name='medicine-detail'),
    path('medicine/price/create/<int:pk1>', views.PriceCreateView.as_view(), name='medicine-price-create'),
    path('medicine/price/update/<int:pk>/<int:pk1>', views.PriceUpdateView.as_view(), name='medicine-price-update'),
    path('medicine/price/delete/<int:pk>/<int:pk1>', views.PriceDeleteView.as_view(), name='medicine-price-delete'),
    path('dealer/', views.DealerListView.as_view(), name='dealer-list'),
    path('dealer/detail/<int:pk>', views.DealerDetailView.as_view(), name='dealer-detail'),
    path('dealer/create', views.DealerCreateView.as_view(), name='dealer-create'),
    path('dealer/update/<int:pk>', views.DealerUpdateView.as_view(), name='dealer-update'),
    path('dealer/delete/<int:pk>', views.DealerDeleteView.as_view(), name='dealer-delete'),
    path('employee/', views.EmployeeListView.as_view(), name='employee-list'),
    path('employee/detail/<int:pk>', views.EmployeeDetailView.as_view(), name='employee-detail'),
    path('employee/create', views.EmployeeCreateView.as_view(), name='employee-create'),
    path('employee/update/<int:pk>', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee/delete/<int:pk>', views.EmployeeDeleteView.as_view(), name='employee-delete'),
    path('todo/', views.TodoListView.as_view(), name='todo-list'),
    path('todo/create', views.TodoCreateView.as_view(), name='todo-create'),
    path('todo/delete/<int:pk>', views.TodoDeleteView.as_view(), name='todo-delete'),
    path('todo/update/<int:pk>', views.TodoUpdateView.as_view(), name='todo-update'),
    path('todo/detail/<int:pk>', views.TodoDetailView.as_view(), name='todo-detail'),
    path('attendance/', views.AttendanceListView.as_view(), name='attendance-list'),
    path('attendance/create', views.AttendanceCreateView.as_view(), name='attendance-create'),
    path('attendance/delete/<int:pk>', views.AttendanceDeleteView.as_view(), name='attendance-delete'),
    path('attendance/update/<int:pk>', views.AttendanceUpdateView.as_view(), name='attendance-update'),
    path('attendance/detail/<int:pk>', views.AttendanceDetailView.as_view(), name='attendance-detail'),
    path('bill/', views.BillListView.as_view(), name='bill-list'),
    path('bill/create', views.BillCreateView.as_view(), name='bill-create'),
    path('bill/delete/<int:pk>', views.BillDeleteView.as_view(), name='bill-delete'),
    path('bill/update/<int:pk>', views.BillUpdateView.as_view(), name='bill-update'),
    path('bill/detail/<int:pk>', views.BillDetailView.as_view(), name='bill-detail'),
    path('customer/', views.CustomerListView.as_view(), name='customer-list'),
    path('customer/create', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customer/delete/<int:pk>', views.CustomerDeleteView.as_view(), name='customer-delete'),
    path('customer/update/<int:pk>', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/detail/<int:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('pharmacy/', views.PharmacyUpdateView.as_view(), {'pk': 1}, name='pharmacy',),
]